name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:


permissions:
  contents: write # Permite que o workflow escreva no repositório (para atualizar o README)


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: platane/snk@v3
        with:
          github_user_name: Joao-v-Silva7 
          outputs: |
            dist/github-snake.gif
            dist/github-snake-dark.gif?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8eabf2,#6082e6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: github-snake
          path: dist
      - uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const readme = fs.readFileSync('README.md', 'utf8');
            
            const newReadme = readme.replace(/[\s\S]*/, '\n<p align="center">\n  <img src="https://raw.githubusercontent.com/${{ github.repository }}/output/github-snake.gif" alt="GitHub Snake" />\n</p>\n');
            fs.writeFileSync('README.md', newReadme);
            
            await github.rest.repos.createOrUpdateFileContents({
                owner: context.repo.owner,
                repo: context.repo.repo,
                path: 'README.md',
                message: 'Atualização: Trocando para animação GIF da cobra',
                content: Buffer.from(newReadme).toString('base64'),
                sha: (await github.rest.repos.getContent({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    path: 'README.md',
                })).data.sha
            });
