name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: platane/snk@v3
        with:
          github_user_name: Joao-v-Silva7 
          # Gera o GIF animado
          outputs: dist/github-snake.gif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Não precisa mais do github-script complexo. O GIF será referenciado diretamente.

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/github-snake.gif
          git commit -m "Atualização: Gerando GIF animado da cobrinha" || echo "Nada para commitar"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master # Ou main, se o seu branch principal for 'main'
